
//PRODUCT ACTIONS
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const GET_LIST_OF_PRODUCTS = 'GET_LIST_OF_PRODUCTS';
export const GET_LIST_OF_PRODUCTS_SUCCESS = 'GET_LIST_OF_PRODUCTS_SUCCESS';
export const GET_LIST_OF_PRODUCTS_FAILURE = 'GET_LIST_OF_PRODUCTS_FAILURE';
export const GET_PRODUCT = 'GET_PRODUCT';
export const SELECTED_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';


//COMPONENT ACTIONS
export const ADD_COMPONENT = 'ADD_PRODUCT';
export const ADD_COMPONENT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_COMPONENT_FAILURE = 'ADD_PRODUCT_FAILURE';





