admin:
  name: Admin_8113_668167688
  password: 1234
store:
  items:
    - serial: '001'
      name: JetSki
      price: 54800
      desc: Like a bike for the lake
      imageUrls:
        - http://blockapps.net/images/header_logo.png?1_1
        - http://blockapps.net/images/header_logo.png?1_2
        - http://blockapps.net/images/header_logo.png?1_3
        - http://blockapps.net/images/header_logo.png?1_4
    - serial: '002'
      name: Floor Fan
      price: 5678
      desc: Cool you off
      imageUrls:
        - http://blockapps.net/images/header_logo.png?2_1
        - http://blockapps.net/images/header_logo.png?2_2
        - http://blockapps.net/images/header_logo.png?2_3
        - http://blockapps.net/images/header_logo.png?2_4
products:
  - id: d8e2deb4-f3f2-11e6-bc64-92361f002671
    name: Chair
    description: A chair with 4 legs
    manufacturingLocation: Singapore
    manufacturingDate: 01-01-2017
  - id: e22a527c-f3f2-11e6-bc64-92361f002671
    name: Table
    description: A Table with 4 legs
    manufacturingLocation: India
    manufacturingDate: 28-02-2017



