apiDebug: true
password: '1234'
timeout: 90000
contractsPath: ./contracts/
dataFilename: ./config/demo-data.yaml
deployFilename: ./config/tester4.deploy.yaml

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    explorerUrl: http://strato-dev4.blockapps.net/explorer
    stratoUrl: http://strato-dev4.blockapps.net/strato-api
    blocUrl: http://strato-dev4.blockapps.net/bloc
  - id: 1
    explorerUrl: http://13.93.209.59/explorer
    stratoUrl: http://13.93.209.59/strato-api
    blocUrl: http://13.93.209.59/bloc
