apiDebug: false
password: '1234'
timeout: 60000
contractsPath: ./contracts/
dataFilename: ./config/demo-data.yaml
deployFilename: ./config/localhost.deploy.yaml

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    #blocUrl: 'http://0.0.0.0:8001'
    explorerUrl: 'http://localhost'
    stratoUrl: 'http://localhost/strato-api'
    blocUrl: 'http://localhost/bloc'
    searchUrl: 'http://localhost/cirrus'
    #blocUrl: 'http://localhost:8000'
