apiDebug: false
password: '1234'
timeout: 20000
contractsPath: ./contracts/
dataFilename: ./config/demo-data.yaml
deployFilename: ./config/tester8.deploy.yaml

# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    #blocUrl: 'http://0.0.0.0:8001'
    explorerUrl: 'http://tester8.centralus.cloudapp.azure.com:9000'
    stratoUrl: 'http://tester8.centralus.cloudapp.azure.com/strato-api'
    blocUrl: 'http://tester8.centralus.cloudapp.azure.com/bloc'
    searchUrl: 'http://tester8.centralus.cloudapp.azure.com/cirrus'
