apiDebug: false
password: '1234'
timeout: 20000
contractsPath: ./contracts/
deployFilename: ./config/tester13.deploy.yaml
data: ./config/data.yaml
multiNode: false
# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    #blocUrl: 'http://0.0.0.0:8000'
    explorerUrl: 'http://tester13.eastus.cloudapp.azure.com/explorer'
    stratoUrl: 'http://tester13.eastus.cloudapp.azure.com/strato-api'
    blocUrl: 'http://tester13.eastus.cloudapp.azure.com:8000'
    searchUrl: 'http://tester13.eastus.cloudapp.azure.com/cirrus'